/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module alu_4_bit(A, B, clk, rst, mode, y);
  wire [7:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  wire _412_;
  wire _413_;
  wire _414_;
  wire _415_;
  wire _416_;
  wire _417_;
  wire _418_;
  wire _419_;
  wire _420_;
  wire _421_;
  wire _422_;
  wire _423_;
  wire _424_;
  wire _425_;
  wire _426_;
  wire _427_;
  wire _428_;
  wire _429_;
  wire _430_;
  wire _431_;
  wire _432_;
  wire _433_;
  wire _434_;
  wire _435_;
  wire _436_;
  wire _437_;
  wire _438_;
  wire _439_;
  wire _440_;
  wire _441_;
  wire _442_;
  wire _443_;
  wire _444_;
  wire _445_;
  wire _446_;
  wire _447_;
  wire _448_;
  wire _449_;
  wire _450_;
  wire _451_;
  wire _452_;
  wire _453_;
  wire _454_;
  wire _455_;
  wire _456_;
  wire _457_;
  wire _458_;
  wire _459_;
  wire _460_;
  wire _461_;
  wire _462_;
  wire _463_;
  wire _464_;
  wire _465_;
  wire _466_;
  wire _467_;
  wire _468_;
  wire _469_;
  wire _470_;
  wire _471_;
  wire _472_;
  wire _473_;
  wire _474_;
  wire _475_;
  wire _476_;
  wire _477_;
  wire _478_;
  wire _479_;
  wire _480_;
  wire _481_;
  wire _482_;
  wire _483_;
  wire _484_;
  wire _485_;
  wire _486_;
  wire _487_;
  wire _488_;
  wire _489_;
  wire _490_;
  wire _491_;
  wire _492_;
  wire _493_;
  wire _494_;
  wire _495_;
  wire _496_;
  wire _497_;
  wire _498_;
  wire _499_;
  wire _500_;
  wire _501_;
  wire _502_;
  wire _503_;
  wire _504_;
  wire _505_;
  wire _506_;
  wire _507_;
  wire _508_;
  wire _509_;
  wire _510_;
  wire _511_;
  wire _512_;
  wire _513_;
  wire _514_;
  wire _515_;
  wire _516_;
  wire _517_;
  wire _518_;
  wire _519_;
  wire _520_;
  wire _521_;
  wire _522_;
  wire _523_;
  wire _524_;
  wire _525_;
  wire _526_;
  wire _527_;
  wire _528_;
  wire _529_;
  wire _530_;
  wire _531_;
  wire _532_;
  wire _533_;
  wire _534_;
  wire _535_;
  wire _536_;
  wire _537_;
  wire _538_;
  wire _539_;
  wire _540_;
  wire _541_;
  wire _542_;
  wire _543_;
  wire _544_;
  wire _545_;
  wire _546_;
  wire _547_;
  wire _548_;
  wire _549_;
  wire _550_;
  wire _551_;
  wire _552_;
  wire _553_;
  wire _554_;
  wire _555_;
  wire _556_;
  wire _557_;
  wire _558_;
  wire _559_;
  wire _560_;
  wire _561_;
  wire _562_;
  wire _563_;
  wire _564_;
  wire _565_;
  wire _566_;
  wire _567_;
  wire _568_;
  wire _569_;
  wire _570_;
  wire _571_;
  wire _572_;
  wire _573_;
  wire _574_;
  wire _575_;
  wire _576_;
  wire _577_;
  wire _578_;
  wire _579_;
  wire _580_;
  wire _581_;
  wire _582_;
  wire _583_;
  wire _584_;
  wire _585_;
  wire _586_;
  wire _587_;
  wire _588_;
  wire _589_;
  wire _590_;
  wire _591_;
  wire _592_;
  wire _593_;
  input [3:0] A;
  input [3:0] B;
  input clk;
  input [2:0] mode;
  input rst;
  output [7:0] y;
  reg [7:0] y;
  sky130_fd_sc_hd__clkinv_1 _594_ (
    .A(_441_),
    .Y(_516_)
  );
  sky130_fd_sc_hd__clkinv_1 _595_ (
    .A(_440_),
    .Y(_517_)
  );
  sky130_fd_sc_hd__clkinv_1 _596_ (
    .A(_442_),
    .Y(_518_)
  );
  sky130_fd_sc_hd__nor2_1 _597_ (
    .A(_516_),
    .B(_437_),
    .Y(_519_)
  );
  sky130_fd_sc_hd__nor2_1 _598_ (
    .A(_442_),
    .B(_519_),
    .Y(_520_)
  );
  sky130_fd_sc_hd__nor2_1 _599_ (
    .A(_444_),
    .B(_443_),
    .Y(_521_)
  );
  sky130_fd_sc_hd__nand2b_1 _600_ (
    .A_N(_439_),
    .B(_441_),
    .Y(_522_)
  );
  sky130_fd_sc_hd__nand2_1 _601_ (
    .A(_440_),
    .B(_442_),
    .Y(_523_)
  );
  sky130_fd_sc_hd__or3_1 _602_ (
    .A(_444_),
    .B(_443_),
    .C(_442_),
    .X(_524_)
  );
  sky130_fd_sc_hd__o21ai_0 _603_ (
    .A1(_516_),
    .A2(_524_),
    .B1(_440_),
    .Y(_525_)
  );
  sky130_fd_sc_hd__nand2_1 _604_ (
    .A(_441_),
    .B(_439_),
    .Y(_526_)
  );
  sky130_fd_sc_hd__o221ai_1 _605_ (
    .A1(_516_),
    .A2(_439_),
    .B1(_518_),
    .B2(_440_),
    .C1(_521_),
    .Y(_527_)
  );
  sky130_fd_sc_hd__o2111ai_1 _606_ (
    .A1(_440_),
    .A2(_518_),
    .B1(_521_),
    .C1(_439_),
    .D1(_441_),
    .Y(_528_)
  );
  sky130_fd_sc_hd__and2_0 _607_ (
    .A(_439_),
    .B(_528_),
    .X(_529_)
  );
  sky130_fd_sc_hd__nand2_1 _608_ (
    .A(_439_),
    .B(_528_),
    .Y(_530_)
  );
  sky130_fd_sc_hd__nor2_1 _609_ (
    .A(_516_),
    .B(_438_),
    .Y(_531_)
  );
  sky130_fd_sc_hd__xnor2_1 _610_ (
    .A(_518_),
    .B(_529_),
    .Y(_532_)
  );
  sky130_fd_sc_hd__nor2_1 _611_ (
    .A(_531_),
    .B(_532_),
    .Y(_533_)
  );
  sky130_fd_sc_hd__maj3_1 _612_ (
    .A(_442_),
    .B(_530_),
    .C(_531_),
    .X(_534_)
  );
  sky130_fd_sc_hd__a41oi_1 _613_ (
    .A1(_440_),
    .A2(_442_),
    .A3(_521_),
    .A4(_522_),
    .B1(_525_),
    .Y(_535_)
  );
  sky130_fd_sc_hd__o21ba_1 _614_ (
    .A1(_443_),
    .A2(_534_),
    .B1_N(_535_),
    .X(_536_)
  );
  sky130_fd_sc_hd__o21bai_1 _615_ (
    .A1(_443_),
    .A2(_534_),
    .B1_N(_535_),
    .Y(_537_)
  );
  sky130_fd_sc_hd__a21oi_1 _616_ (
    .A1(_443_),
    .A2(_534_),
    .B1(_444_),
    .Y(_538_)
  );
  sky130_fd_sc_hd__a21o_1 _617_ (
    .A1(_443_),
    .A2(_534_),
    .B1(_444_),
    .X(_539_)
  );
  sky130_fd_sc_hd__o31ai_1 _618_ (
    .A1(_516_),
    .A2(_536_),
    .A3(_539_),
    .B1(_438_),
    .Y(_540_)
  );
  sky130_fd_sc_hd__a31oi_1 _619_ (
    .A1(_531_),
    .A2(_537_),
    .A3(_538_),
    .B1(_520_),
    .Y(_541_)
  );
  sky130_fd_sc_hd__nand2_1 _620_ (
    .A(_531_),
    .B(_532_),
    .Y(_542_)
  );
  sky130_fd_sc_hd__nand4b_1 _621_ (
    .A_N(_533_),
    .B(_537_),
    .C(_538_),
    .D(_542_),
    .Y(_543_)
  );
  sky130_fd_sc_hd__o21ai_0 _622_ (
    .A1(_536_),
    .A2(_539_),
    .B1(_529_),
    .Y(_544_)
  );
  sky130_fd_sc_hd__nand3_1 _623_ (
    .A(_443_),
    .B(_543_),
    .C(_544_),
    .Y(_545_)
  );
  sky130_fd_sc_hd__nand2_1 _624_ (
    .A(_442_),
    .B(_519_),
    .Y(_546_)
  );
  sky130_fd_sc_hd__a21boi_0 _625_ (
    .A1(_540_),
    .A2(_541_),
    .B1_N(_546_),
    .Y(_547_)
  );
  sky130_fd_sc_hd__a21oi_1 _626_ (
    .A1(_543_),
    .A2(_544_),
    .B1(_443_),
    .Y(_548_)
  );
  sky130_fd_sc_hd__xnor2_1 _627_ (
    .A(_443_),
    .B(_534_),
    .Y(_549_)
  );
  sky130_fd_sc_hd__nand2_1 _628_ (
    .A(_535_),
    .B(_549_),
    .Y(_550_)
  );
  sky130_fd_sc_hd__nor2_1 _629_ (
    .A(_444_),
    .B(_550_),
    .Y(_551_)
  );
  sky130_fd_sc_hd__a211o_1 _630_ (
    .A1(_545_),
    .A2(_547_),
    .B1(_548_),
    .C1(_551_),
    .X(_552_)
  );
  sky130_fd_sc_hd__nand2_1 _631_ (
    .A(_446_),
    .B(_445_),
    .Y(_553_)
  );
  sky130_fd_sc_hd__nor2_1 _632_ (
    .A(_447_),
    .B(_553_),
    .Y(_554_)
  );
  sky130_fd_sc_hd__nand2_1 _633_ (
    .A(_444_),
    .B(_525_),
    .Y(_555_)
  );
  sky130_fd_sc_hd__nor2_1 _634_ (
    .A(_441_),
    .B(_437_),
    .Y(_556_)
  );
  sky130_fd_sc_hd__nand2b_1 _635_ (
    .A_N(_446_),
    .B(_447_),
    .Y(_557_)
  );
  sky130_fd_sc_hd__nand3b_1 _636_ (
    .A_N(_446_),
    .B(_445_),
    .C(_447_),
    .Y(_558_)
  );
  sky130_fd_sc_hd__nand2_1 _637_ (
    .A(_441_),
    .B(_437_),
    .Y(_559_)
  );
  sky130_fd_sc_hd__nor2_1 _638_ (
    .A(_447_),
    .B(_446_),
    .Y(_560_)
  );
  sky130_fd_sc_hd__and3b_1 _639_ (
    .A_N(_445_),
    .B(_446_),
    .C(_447_),
    .X(_561_)
  );
  sky130_fd_sc_hd__o21ai_0 _640_ (
    .A1(_560_),
    .A2(_561_),
    .B1(_559_),
    .Y(_562_)
  );
  sky130_fd_sc_hd__a21oi_1 _641_ (
    .A1(_558_),
    .A2(_562_),
    .B1(_556_),
    .Y(_563_)
  );
  sky130_fd_sc_hd__nor3b_1 _642_ (
    .A(_447_),
    .B(_445_),
    .C_N(_446_),
    .Y(_564_)
  );
  sky130_fd_sc_hd__or3b_1 _643_ (
    .A(_447_),
    .B(_445_),
    .C_N(_446_),
    .X(_565_)
  );
  sky130_fd_sc_hd__nor2_1 _644_ (
    .A(_445_),
    .B(_557_),
    .Y(_566_)
  );
  sky130_fd_sc_hd__nor2_1 _645_ (
    .A(_564_),
    .B(_566_),
    .Y(_567_)
  );
  sky130_fd_sc_hd__nand3_1 _646_ (
    .A(_447_),
    .B(_446_),
    .C(_445_),
    .Y(_568_)
  );
  sky130_fd_sc_hd__o22ai_1 _647_ (
    .A1(_559_),
    .A2(_567_),
    .B1(_568_),
    .B2(_437_),
    .Y(_569_)
  );
  sky130_fd_sc_hd__a311o_1 _648_ (
    .A1(_552_),
    .A2(_554_),
    .A3(_555_),
    .B1(_563_),
    .C1(_569_),
    .X(_429_)
  );
  sky130_fd_sc_hd__nand3_1 _649_ (
    .A(_537_),
    .B(_538_),
    .C(_554_),
    .Y(_570_)
  );
  sky130_fd_sc_hd__nand2_1 _650_ (
    .A(_445_),
    .B(_560_),
    .Y(_571_)
  );
  sky130_fd_sc_hd__nor2_1 _651_ (
    .A(_442_),
    .B(_438_),
    .Y(_572_)
  );
  sky130_fd_sc_hd__and2_0 _652_ (
    .A(_442_),
    .B(_438_),
    .X(_573_)
  );
  sky130_fd_sc_hd__nand2_1 _653_ (
    .A(_442_),
    .B(_438_),
    .Y(_574_)
  );
  sky130_fd_sc_hd__nor2_1 _654_ (
    .A(_572_),
    .B(_573_),
    .Y(_575_)
  );
  sky130_fd_sc_hd__xnor2_1 _655_ (
    .A(_519_),
    .B(_575_),
    .Y(_576_)
  );
  sky130_fd_sc_hd__nor2_1 _656_ (
    .A(_571_),
    .B(_576_),
    .Y(_577_)
  );
  sky130_fd_sc_hd__a22oi_1 _657_ (
    .A1(_437_),
    .A2(_442_),
    .B1(_438_),
    .B2(_441_),
    .Y(_578_)
  );
  sky130_fd_sc_hd__o21ai_0 _658_ (
    .A1(_559_),
    .A2(_574_),
    .B1(_564_),
    .Y(_579_)
  );
  sky130_fd_sc_hd__nor2_1 _659_ (
    .A(_578_),
    .B(_579_),
    .Y(_580_)
  );
  sky130_fd_sc_hd__nor3_1 _660_ (
    .A(_559_),
    .B(_572_),
    .C(_573_),
    .Y(_581_)
  );
  sky130_fd_sc_hd__nor3_1 _661_ (
    .A(_447_),
    .B(_446_),
    .C(_445_),
    .Y(_582_)
  );
  sky130_fd_sc_hd__a21oi_1 _662_ (
    .A1(_441_),
    .A2(_437_),
    .B1(_575_),
    .Y(_583_)
  );
  sky130_fd_sc_hd__nor2_1 _663_ (
    .A(_581_),
    .B(_583_),
    .Y(_584_)
  );
  sky130_fd_sc_hd__nand2_1 _664_ (
    .A(_582_),
    .B(_584_),
    .Y(_585_)
  );
  sky130_fd_sc_hd__nand2_1 _665_ (
    .A(_561_),
    .B(_575_),
    .Y(_586_)
  );
  sky130_fd_sc_hd__o221ai_1 _666_ (
    .A1(_438_),
    .A2(_568_),
    .B1(_572_),
    .B2(_558_),
    .C1(_586_),
    .Y(_587_)
  );
  sky130_fd_sc_hd__a2111oi_0 _667_ (
    .A1(_566_),
    .A2(_573_),
    .B1(_577_),
    .C1(_580_),
    .D1(_587_),
    .Y(_588_)
  );
  sky130_fd_sc_hd__nand3_1 _668_ (
    .A(_570_),
    .B(_585_),
    .C(_588_),
    .Y(_430_)
  );
  sky130_fd_sc_hd__nor3_1 _669_ (
    .A(_447_),
    .B(_527_),
    .C(_553_),
    .Y(_589_)
  );
  sky130_fd_sc_hd__nand2_1 _670_ (
    .A(_437_),
    .B(_443_),
    .Y(_590_)
  );
  sky130_fd_sc_hd__nand2_1 _671_ (
    .A(_439_),
    .B(_442_),
    .Y(_591_)
  );
  sky130_fd_sc_hd__xnor3_1 _672_ (
    .A(_526_),
    .B(_573_),
    .C(_590_),
    .X(_592_)
  );
  sky130_fd_sc_hd__or3_1 _673_ (
    .A(_559_),
    .B(_574_),
    .C(_592_),
    .X(_593_)
  );
  sky130_fd_sc_hd__o21ai_0 _674_ (
    .A1(_559_),
    .A2(_574_),
    .B1(_592_),
    .Y(_448_)
  );
  sky130_fd_sc_hd__nand2_1 _675_ (
    .A(_439_),
    .B(_443_),
    .Y(_449_)
  );
  sky130_fd_sc_hd__nor2_1 _676_ (
    .A(_439_),
    .B(_443_),
    .Y(_450_)
  );
  sky130_fd_sc_hd__xor2_1 _677_ (
    .A(_439_),
    .B(_443_),
    .X(_451_)
  );
  sky130_fd_sc_hd__nor3_1 _678_ (
    .A(_573_),
    .B(_581_),
    .C(_451_),
    .Y(_452_)
  );
  sky130_fd_sc_hd__o21ai_0 _679_ (
    .A1(_573_),
    .A2(_581_),
    .B1(_451_),
    .Y(_453_)
  );
  sky130_fd_sc_hd__nand2_1 _680_ (
    .A(_582_),
    .B(_453_),
    .Y(_454_)
  );
  sky130_fd_sc_hd__a21oi_1 _681_ (
    .A1(_438_),
    .A2(_546_),
    .B1(_520_),
    .Y(_455_)
  );
  sky130_fd_sc_hd__xnor2_1 _682_ (
    .A(_451_),
    .B(_455_),
    .Y(_456_)
  );
  sky130_fd_sc_hd__a21oi_1 _683_ (
    .A1(_439_),
    .A2(_443_),
    .B1(_445_),
    .Y(_457_)
  );
  sky130_fd_sc_hd__o32ai_1 _684_ (
    .A1(_557_),
    .A2(_450_),
    .A3(_457_),
    .B1(_568_),
    .B2(_439_),
    .Y(_458_)
  );
  sky130_fd_sc_hd__a21oi_1 _685_ (
    .A1(_561_),
    .A2(_451_),
    .B1(_458_),
    .Y(_459_)
  );
  sky130_fd_sc_hd__o21ai_0 _686_ (
    .A1(_452_),
    .A2(_454_),
    .B1(_459_),
    .Y(_460_)
  );
  sky130_fd_sc_hd__a311oi_1 _687_ (
    .A1(_564_),
    .A2(_593_),
    .A3(_448_),
    .B1(_460_),
    .C1(_589_),
    .Y(_461_)
  );
  sky130_fd_sc_hd__o21ai_0 _688_ (
    .A1(_571_),
    .A2(_456_),
    .B1(_461_),
    .Y(_431_)
  );
  sky130_fd_sc_hd__nand2_1 _689_ (
    .A(_444_),
    .B(_535_),
    .Y(_462_)
  );
  sky130_fd_sc_hd__clkinv_1 _690_ (
    .A(_462_),
    .Y(_463_)
  );
  sky130_fd_sc_hd__nor2_1 _691_ (
    .A(_440_),
    .B(_444_),
    .Y(_464_)
  );
  sky130_fd_sc_hd__o21ai_0 _692_ (
    .A1(_440_),
    .A2(_444_),
    .B1(_462_),
    .Y(_465_)
  );
  sky130_fd_sc_hd__nand3_1 _693_ (
    .A(_449_),
    .B(_453_),
    .C(_465_),
    .Y(_466_)
  );
  sky130_fd_sc_hd__nor3b_1 _694_ (
    .A(_463_),
    .B(_464_),
    .C_N(_561_),
    .Y(_467_)
  );
  sky130_fd_sc_hd__a21oi_1 _695_ (
    .A1(_449_),
    .A2(_453_),
    .B1(_465_),
    .Y(_468_)
  );
  sky130_fd_sc_hd__nor2b_1 _696_ (
    .A(_468_),
    .B_N(_582_),
    .Y(_469_)
  );
  sky130_fd_sc_hd__o21ai_0 _697_ (
    .A1(_467_),
    .A2(_469_),
    .B1(_466_),
    .Y(_470_)
  );
  sky130_fd_sc_hd__nand2b_1 _698_ (
    .A_N(_443_),
    .B(_439_),
    .Y(_471_)
  );
  sky130_fd_sc_hd__o21ai_0 _699_ (
    .A1(_451_),
    .A2(_455_),
    .B1(_471_),
    .Y(_472_)
  );
  sky130_fd_sc_hd__a21oi_1 _700_ (
    .A1(_465_),
    .A2(_472_),
    .B1(_571_),
    .Y(_473_)
  );
  sky130_fd_sc_hd__o21ai_0 _701_ (
    .A1(_465_),
    .A2(_472_),
    .B1(_473_),
    .Y(_474_)
  );
  sky130_fd_sc_hd__nand2_1 _702_ (
    .A(_437_),
    .B(_444_),
    .Y(_475_)
  );
  sky130_fd_sc_hd__maj3_1 _703_ (
    .A(_526_),
    .B(_574_),
    .C(_590_),
    .X(_476_)
  );
  sky130_fd_sc_hd__nand2_1 _704_ (
    .A(_443_),
    .B(_438_),
    .Y(_477_)
  );
  sky130_fd_sc_hd__nand2_1 _705_ (
    .A(_441_),
    .B(_440_),
    .Y(_478_)
  );
  sky130_fd_sc_hd__xor3_1 _706_ (
    .A(_591_),
    .B(_477_),
    .C(_478_),
    .X(_479_)
  );
  sky130_fd_sc_hd__xor3_1 _707_ (
    .A(_475_),
    .B(_476_),
    .C(_479_),
    .X(_480_)
  );
  sky130_fd_sc_hd__nand2_1 _708_ (
    .A(_593_),
    .B(_480_),
    .Y(_481_)
  );
  sky130_fd_sc_hd__nor2_1 _709_ (
    .A(_593_),
    .B(_480_),
    .Y(_482_)
  );
  sky130_fd_sc_hd__nand2_1 _710_ (
    .A(_564_),
    .B(_481_),
    .Y(_483_)
  );
  sky130_fd_sc_hd__a21oi_1 _711_ (
    .A1(_441_),
    .A2(_517_),
    .B1(_524_),
    .Y(_484_)
  );
  sky130_fd_sc_hd__o22ai_1 _712_ (
    .A1(_440_),
    .A2(_568_),
    .B1(_464_),
    .B2(_558_),
    .Y(_485_)
  );
  sky130_fd_sc_hd__a21oi_1 _713_ (
    .A1(_554_),
    .A2(_484_),
    .B1(_485_),
    .Y(_486_)
  );
  sky130_fd_sc_hd__o21ai_0 _714_ (
    .A1(_482_),
    .A2(_483_),
    .B1(_486_),
    .Y(_487_)
  );
  sky130_fd_sc_hd__a21oi_1 _715_ (
    .A1(_566_),
    .A2(_463_),
    .B1(_487_),
    .Y(_488_)
  );
  sky130_fd_sc_hd__nand3_1 _716_ (
    .A(_470_),
    .B(_474_),
    .C(_488_),
    .Y(_432_)
  );
  sky130_fd_sc_hd__o21ai_0 _717_ (
    .A1(_517_),
    .A2(_444_),
    .B1(_473_),
    .Y(_489_)
  );
  sky130_fd_sc_hd__o311a_1 _718_ (
    .A1(_441_),
    .A2(_524_),
    .A3(_553_),
    .B1(_568_),
    .C1(_489_),
    .X(_490_)
  );
  sky130_fd_sc_hd__o21ai_0 _719_ (
    .A1(_463_),
    .A2(_468_),
    .B1(_582_),
    .Y(_491_)
  );
  sky130_fd_sc_hd__maj3_1 _720_ (
    .A(_475_),
    .B(_476_),
    .C(_479_),
    .X(_492_)
  );
  sky130_fd_sc_hd__nand2_1 _721_ (
    .A(_444_),
    .B(_438_),
    .Y(_493_)
  );
  sky130_fd_sc_hd__maj3_1 _722_ (
    .A(_591_),
    .B(_477_),
    .C(_478_),
    .X(_494_)
  );
  sky130_fd_sc_hd__xnor2_1 _723_ (
    .A(_523_),
    .B(_449_),
    .Y(_495_)
  );
  sky130_fd_sc_hd__xor3_1 _724_ (
    .A(_493_),
    .B(_494_),
    .C(_495_),
    .X(_496_)
  );
  sky130_fd_sc_hd__nor2_1 _725_ (
    .A(_492_),
    .B(_496_),
    .Y(_497_)
  );
  sky130_fd_sc_hd__xor2_1 _726_ (
    .A(_492_),
    .B(_496_),
    .X(_498_)
  );
  sky130_fd_sc_hd__a21oi_1 _727_ (
    .A1(_482_),
    .A2(_498_),
    .B1(_565_),
    .Y(_499_)
  );
  sky130_fd_sc_hd__o21ai_0 _728_ (
    .A1(_482_),
    .A2(_498_),
    .B1(_499_),
    .Y(_500_)
  );
  sky130_fd_sc_hd__nand3_1 _729_ (
    .A(_490_),
    .B(_491_),
    .C(_500_),
    .Y(_433_)
  );
  sky130_fd_sc_hd__a21oi_1 _730_ (
    .A1(_482_),
    .A2(_498_),
    .B1(_497_),
    .Y(_501_)
  );
  sky130_fd_sc_hd__maj3_1 _731_ (
    .A(_493_),
    .B(_494_),
    .C(_495_),
    .X(_502_)
  );
  sky130_fd_sc_hd__nand2_1 _732_ (
    .A(_439_),
    .B(_444_),
    .Y(_503_)
  );
  sky130_fd_sc_hd__nand3_1 _733_ (
    .A(_440_),
    .B(_443_),
    .C(_591_),
    .Y(_504_)
  );
  sky130_fd_sc_hd__xor2_1 _734_ (
    .A(_503_),
    .B(_504_),
    .X(_505_)
  );
  sky130_fd_sc_hd__nor2b_1 _735_ (
    .A(_502_),
    .B_N(_505_),
    .Y(_506_)
  );
  sky130_fd_sc_hd__xnor2_1 _736_ (
    .A(_502_),
    .B(_505_),
    .Y(_507_)
  );
  sky130_fd_sc_hd__nor2b_1 _737_ (
    .A(_501_),
    .B_N(_507_),
    .Y(_508_)
  );
  sky130_fd_sc_hd__nor2b_1 _738_ (
    .A(_507_),
    .B_N(_501_),
    .Y(_509_)
  );
  sky130_fd_sc_hd__o31ai_1 _739_ (
    .A1(_565_),
    .A2(_508_),
    .A3(_509_),
    .B1(_490_),
    .Y(_434_)
  );
  sky130_fd_sc_hd__o2111ai_1 _740_ (
    .A1(_444_),
    .A2(_442_),
    .B1(_443_),
    .C1(_440_),
    .D1(_439_),
    .Y(_510_)
  );
  sky130_fd_sc_hd__nor2_1 _741_ (
    .A(_462_),
    .B(_510_),
    .Y(_511_)
  );
  sky130_fd_sc_hd__xor2_1 _742_ (
    .A(_462_),
    .B(_510_),
    .X(_512_)
  );
  sky130_fd_sc_hd__o21a_1 _743_ (
    .A1(_506_),
    .A2(_508_),
    .B1(_512_),
    .X(_513_)
  );
  sky130_fd_sc_hd__o31ai_1 _744_ (
    .A1(_506_),
    .A2(_508_),
    .A3(_512_),
    .B1(_564_),
    .Y(_514_)
  );
  sky130_fd_sc_hd__o21ai_0 _745_ (
    .A1(_513_),
    .A2(_514_),
    .B1(_490_),
    .Y(_435_)
  );
  sky130_fd_sc_hd__o21ai_0 _746_ (
    .A1(_511_),
    .A2(_513_),
    .B1(_564_),
    .Y(_515_)
  );
  sky130_fd_sc_hd__nand2_1 _747_ (
    .A(_490_),
    .B(_515_),
    .Y(_436_)
  );
  always @(posedge clk)
      y[0] <= _000_[0];
  always @(posedge clk)
      y[1] <= _000_[1];
  always @(posedge clk)
      y[2] <= _000_[2];
  always @(posedge clk)
      y[3] <= _000_[3];
  always @(posedge clk)
      y[4] <= _000_[4];
  always @(posedge clk)
      y[5] <= _000_[5];
  always @(posedge clk)
      y[6] <= _000_[6];
  always @(posedge clk)
      y[7] <= _000_[7];
  assign _441_ = B[0];
  assign _437_ = A[0];
  assign _447_ = mode[2];
  assign _446_ = mode[1];
  assign _445_ = mode[0];
  assign _440_ = A[3];
  assign _439_ = A[2];
  assign _444_ = B[3];
  assign _443_ = B[2];
  assign _442_ = B[1];
  assign _438_ = A[1];
  assign _000_[0] = _429_;
  assign _000_[1] = _430_;
  assign _000_[2] = _431_;
  assign _000_[3] = _432_;
  assign _000_[4] = _433_;
  assign _000_[5] = _434_;
  assign _000_[6] = _435_;
  assign _000_[7] = _436_;
endmodule
